In [1]:
import os
import sys

project_root = os.path.abspath("..")   # if the notebook is inside notebooks/
sys.path.insert(0, project_root)
print(project_root)

c:\Projects\Service Event Framework\Improvement\code

In [2]:
import os
import numpy as np
import pandas as pd
from utils.dbconnection import engine
from pathlib import Path
from utils.config import config

2026-10-08 10:48:20,932 - Logger: Log file: c:\Projects\Service Event Framework\Improvement\code\logs\SEF_Improvement_20261008_104820.log
2026-10-08 10:48:20,958 - SQLAlchemy: Database connection configured successfully!

In [87]:
parent = os.path.join(config.locations.inputs, "material_as_parent_child.csv")
df_parent = pd.read_csv(parent)
df_parent.columns = ['parent_material', 'child_material']
order_count_path = os.path.join(config.locations.inputs, "Material_Order_Counts_v2.xlsx")
df_order_counts = pd.read_excel(order_count_path)

In [88]:
df_parent.head(2), df_order_counts.head(2)

(  parent_material child_material
 0          100223         109283
 1          101110         153184,
    Material                    MaterialText  order_counts
 0    131496            CON SP S G1(M)XG1(F)           846
 1  10212870  GREASE COLLECTING CAN W. COVER          2795)

Availability of common Materials

In [126]:
df_parent['parent_material'].nunique(), df_parent['child_material'].nunique()

(2532, 7741)

In [127]:
child_pres = df_order_counts.merge(df_parent, left_on='Material', right_on='child_material', how='inner')
par_pres = df_order_counts.merge(df_parent, left_on='Material', right_on='parent_material', how='inner')
child_pres.shape, par_pres.shape

((1284, 5), (221, 5))

In [89]:
xlsx_path = os.path.join(config.locations.outputs, "service_event_analysis.xlsx")
df = pd.read_excel(xlsx_path, sheet_name="event_material")
df.head()

,DServiceEventID,Serviceeventcode,ServiceEventName,AND_OR,Priority,confidence,Itemnumber,MaterialName,MaterialGroup,MaterialGroupDescription
0,1,BladeBearingReplace,Blade Bearing Replacement,OR,9.6,10,107033,BLADE BEARING ø54,31,"Bearings, Blade TRAC"
1,1,BladeBearingReplace,Blade Bearing Replacement,OR,9.6,10,760306,BLADE BEARING MODULE,327,Nacelle modules and
2,1,BladeBearingReplace,Blade Bearing Replacement,OR,9.6,10,76221907,BLADE BEARING MODULE,30,Bearings
3,1,BladeBearingReplace,Blade Bearing Replacement,OR,9.6,10,76221971,BLADE BEARING MODULE,327,Nacelle modules and
4,4,GenBearReplace,Generator Bearing Replacement,OR,7.8,10,103566,"BEARING,BALL,6344 MC3,220 mm",30,Bearings

In [90]:
df['Serviceeventcode'].nunique()

486

In [91]:
events = ",".join("'" + df['Serviceeventcode'].unique().astype(str) + "'")
events

"'BladeBearingReplace','GenBearReplace','MainBearingReplace','PitchCylinderReplace','PropValveReplace','YawGearReplace','GearIMS','GearHSS','GearPlanetaryStage','GearPT100SensorReplace','GearPitchTubeLeakRepair','GenFanReplace','CACPumpReplace','CACLiquidConsumption','HydOilConsumption','HydMotorReplace','HydPumpReplace','GearOilConsumption','TrafOilConsumption','YawMotorReplace','ServiceLiftMotorReplace','CoolingSystemFanMotorReplace','GearLubeMotorReplace','CoolerTopReplace','SpinnerNoseConeReplace','WindvaneSensorReplace','CACPressSensorReplace','CCISensorReplace','CACSensorReplace','PPRSensorReplace','CCICBReplace','LPCCBReplace','PPRCBReplace','YAWCBReplace','CCIKitsetConsumption','NLEKitsetConsumption','PTRKitsetConsumption','YAWKitsetConsumption','GenBrushReplace','GenRotUnitAdaptorReplace','GbxRepairAdhesiveConsume','PPRCimUpgrCBReplace','PPRContactorReplace','PPRSkiipReplace','BBGreaseConsumption','GenGreaseConsumption','HydLubConsumption','MBAGreaseConsumption','TLFLubConsumption','YawBearGreaseConsumption','YawLubConsumption','NLEGreaseConsumption','APSUPSReplace','NLEBatteryReplace','SCADAUPSReplace','TLFBatteryReplace','TLFUPSReplace','CCIctIOModReplace','CCIctModuleReplace','NLEctModCounterReplace','NLEctModReplace','PPRctModuleReplace','TLFctModuleReplace','WICctModuleReplace','SCADACableReplace','TDCKitSetCableReplace','CIM3135UpgrdCableReplace','PTRW29ConnCableReplace','TLFRawCable Replace','CIM1016CableReplace','CIM2767UpgrdCable Replace','HubCANCableReplace','EmergLightElementReplace','NLEAviationLampReplace','WICLightElementReplace','CCIRelayReplace','NLERelayReplace','NLEARCRelayReplace','PPRRelayReplace','WICRelayReplace','BBGreaseCoupling','BBGreasePumpReplace','CACBlowerReplace','CACClimateModule','ConvertorModReplace','GearLubePumpReplace','GearLubFilterPumpReplace','GenGreasePumpReplace','GenInterfaceModReplace','InternalCraneReplace','InternalHoistReplace','MBAGreasePumpReplace','TowerAccesoriesConsume','VibrDamperReplace','YawGreasePumpReplace','PTRRtrCableReplace','ConvCoolingFanReplace','PowCabCoolFanReplace','TrafoCabCoolFanReplace','PPRHVCableReplace','PPRCapcitorReplace','NLESmokeDetectorReplace','PPRCBPowerPlugReplace','WICPitchSensorReplace','NLEPCEquipReplace','PPRRearConnReplace','NLEContactorReplace','PPRCBPowerPackReplace','TermCrmpPowCabReplace','SkyLightReplace','PIARodEndBearingReplace','PIAHydrStationSerKitsetConsume','CACCoolantFilterReplace','CACCoolantTankReplace','PIAHydrValveReplace','NLESealReplace','HubPowSupplyCompReplace','NLEPowSupplyCompReplace','PowSupplyCompReplace','CCIPCEquipmentReplace','CableReplace','CIM2790WireKitConsumption','NLECableReplace','CTTowAccReplace','YawWormGearTLReplace','SwGReplace','ConnSOWEReplace','HydCoolPipeReplace','RTMHosesReplace','SkyLightCoverReplace','DCCapReplace','PPRacCapReplace','PPRdcCapReplace','PPRTrafoCapReplace','YawBrakeReplace','GBxBrakeSystemReplace','PitchLockActuatorReplace','PTRRotorLockDiscReplace','CCICableReplace','ConvCableReplace','GenInterfaceCableReplace','PitchHydCableReplace','PTRCableReplace','CAC3wayValveReplace','CheckValveHydCircuitReplace','ControllerCabinetFanReplace','HPUReliefValveReplace','NacelleExhaustFanReplace','SolenoidValveHPUReplace','ThermoValveCACReplace','BusbarEquipmentReplace','CoolingHoseReplace','HubControllerReplace','HubPilzSafetyIOReplace','NonNAFTAsprayConsumption','PitchCylEarthCableReplace','PitchCylDamperReplace','HarmonicFilterReplace','GearLubOfflineFilterReplace','APSUPSControllerMGReplace','CACVentilationMGReplace','CCIScadaMGReplace','PTRSlipringMGReplace','AirCondInstallKitConsumption','AutoLubeMatReplace','CoolingDuctConneReplace','ShadowDetectKitConsumption','TowerFlngeBoltTightng','LightningConductorJumperInstall','YawContrllerAdjustmnt','GroundCntrlReplace','NACCBReplace','YawRingReplace','StickerMobileGearSHCReplace','AnchorAssyReplace','APSUPSLightCtrlReplace','CoolingClampReplace','CACMotorReplace','HydHandRotorLockPump','InternalHoistMotorReplace','GearOilPumpMotorAssyReplace','GenBrgSleeveReplace','HydCouplingPumpReplace','HydOfflinePumpReplace','HydPumpMotorAssyReplace','HydPumpTubeReplace','InternalHoistBrgReplace','TorqueArmBushReplace','PPRCTArcNetModuleReplace','CCITACDecoderReplace','VibrTACGuardReplace','FSSSafetyCylinder','LSCStackMatReplace','MSCStackMatReplace','PPRUPSReplace','ThysitorAssyReplace','PTREncoderReplace','AuxiliaryTrafoReplace','GurneyFlapReplace','SerrationReplace','VortexGeneratorReplace','DeIcingSystemReplace','LeadingEdgeErosionWT','CIM4624KitReplace','CubePowerCoolingFilterReplace','CubePowerTempSensorReplace','RTUBushReplace','CIM3957KitReplace','HydraulicBrakeUpgrade','SpinnerHatchFault','AccumulatorBktBoltReplace','DownConductorCableReplace','HydO-RingReplace','YawClawBeamModuleReplace','CopperCapErosionWTRepair','LeadingEdgeTapeDamageWTRepair','DownConductorCableRepair','DownConductorReceptorRepair','GearOilFilterReplace','HYDOilFilterReplace','PPRHYBRDCableReplace','GBXThermalRepairKit','TopMainBoxPLC_parts','PitchElectricalMaterial','GearOilCoolModule','CoolerElementReplace','YawSpringPackReplace','YawBrgPadReplace','YawClawBeamBoltReplace','HydrPumpToothedRim_mat','HydOilLevelSensor_mat','MBAHubBolt_mat','YawGreaseTray_mat','CompositeDisc_mat','PTRDrainValve_mat','GBXOilLevelSwitch_mat','HubBatteryReplace','BladeBearingSeal_mat','NacelleLinearActuatorReplace','LCCoolantLevelSensorReplace','LCPumpSeal_mat','NacelleHumiditySensor_mat','YawRingTeethRepair','InternalHoistChain_mat','InternalHoistSuspension_mat','InternalElectricalSwitch_mat','InternalMechanicalSwitch_mat','SpinnerNoseBoltReplace','HubControllerCabinetLooseBoltReplace','GBXODMSensorReplace','SCADAEthernetCardReplace','SCADARouterSwitchReplace','BladeLoadSensorReplace','BaseFrameReplace','AVCWoelfelSystemDamperReplace','AviationLightControlModuleReplace','OilSampleCollectionReport','BladeStudAssemblyReplace','GenBearingCassetteReplace','GeneratorPhasePT100SensorRepair','PTRTunedMassDamperRepiar','NacelleTunedMassDamperRepiar','FSSPressureSwitchReplace','GearboxPLCBPinLockRepair','PCEquipmentReplace','NoseConeSealReplace','ControllerResistorReplace','ElectricalConnectorReplace','Hub_Battery_Bracket_Replace','NacelleStudBoltReplace','GearOilMainTankReplace','GearOilInletGBXMBAPressureSensor','GearOilAfterPumpFilterPressureSensor','PTRDrainValveActuator','GearOilTankTemperatureSensor','GBXOilInletTemperatureSensor','MBAOilInletTemperatureSensor','GBXODMPumpMotorReplace','GBXODMPumpReplace','GBXODMFilterReplace','GearOilMotorVFDReplace','GearOilHeatExchangerReplace','HydraulicTankReplace','PowertrainShrinkDiscReplace','GearLubeMotorWithVFDReplace','TowerLadder_mat','PitchPressureTransmitterReplace','GearOilTempControlUnitValveReplace','TowerHatchCylinderReplace','TowerServiceLiftWireRope_mat','TowerDoorRepair','GearLubeInlineFilter','GearOilGravityTankReplace','MBAGreasePumpProximitySensorReplace','MBA Grease Pump Distributor Block Replace','PitchLogicElementReplace','RotorLockPinReplace','RotorLockPumpAssemblyReplace','GearLubeInlineMotorReplace','GridChokeReplace','PitchCylinderSealKitReplace','RotorLockCylinderReplace','SCADAServerReplace','SCADAPowerMeterReplace','CMSAccelationSensorReplace','WindFTSensorReplace','ConverterCurrentSensorReplace','PTRDrainMetalDetectReplace','ConverterThermostatReplace','CMSDDAUModuleReplace','PowerPlantControllerReplace','Controller Contactor Replace','TowerFlangeStudBoltReplace','TowerFlangeHVBoltReplace','RotatingTransferUnitReplace','TowerDehumidifierReplace','SwingGateAssyReplace','LiftGalleryModuleReplace','TowerCableClampAssyReplace','TowerExternalLampMaterial','TowerSeashellBracketsReplace','TowerSupportBraceReplace','TowerWeldBracketsReplace','TowerLadderwithFallSafetyCable','TowerLadderLegsReplace','TowerLadderStileConnectors','TowerLadderAnchorPoint','TowerRailLadder','TowerCableTrayReplace','TowerCableRotationRetainersMaterial','YawMotorFanReplace','ServiceLiftPowerCableReplace','ServiceLiftWireFixBracketSteel','ServiceLiftInterlock','ServiceLiftDoorSwitch','ServiceLiftGateSwitch','ServiceLiftWireFixBracket','ServiceLiftWireTensioningSys','ServiceLiftPilotLight','ServiceLiftContactorPhaseController','ServiceLiftPowerCableBag','TowerServiceLiftReplace','TowerServiceLiftControlBoxReplace','HydraulicPressureSensorReplace','GeneratorBearingPT100SensorRepair','PitchEncoderReplace','NacelleBottomCoverRepair','GBXBrakeCalliperReplace','GBXBrakeShoeReplace','GBXBrakePadReplace','VibrationDamperTrafoFrame','MBAGreaseHoseReplace','CTBatteryModuleReplace','AGODCChopperResistorReplace','GearLubricationControllerCabinetReplace','FireExtinguisherReplace','StairCaseAssemblyReplace','FSSFireDetectionTubeReplace','FireSuppressionSystemReplace','TowerLadderMagnet_mat','TowerStairCaseStabilizerLeg','TowerDoorRubberGasket','TowerStairCaseTread','TowerDoorPneumaticCylinder','TowerWireRopeClamp','TowerDoorRainGutter','TowerLightJunctionBox','TowerDoorVentilationFilter','TowerGrateTrayMagnet','TowerClampSealProfile','TowerNitrileRubber','TowerGalleryLock','TowerLadderJointFittings','TowerDoorLockCover','TowerLadderRubberEnd','TowerLadderRungFitting','TowerGrateTray','TowerInternalLightElementReplace','InternalChainHoistAssembly','APSPowerSupplyTransformerReplace','YawGearOilConsumption','GearLubricationFilterO-RingReplace','ControlPanelFuseFibreGlass','YawTorqueLimiterReplace','GearStayBlockBoltReplace','GearStayBlockAssemblyReplace','IceDectectionSystemReplace','ProgramLogixControllerCPUReplace','CTDCNSafetyModuleReplace','BusLoopModuleReplace','AcousticMaskingControlReplace','YawDriveAssemblyReplace','PowerFactorCorrectionCapacitorReplace','TrafoRoomLockKitReplace','MainShaftCoverOilTrayAssyReplace','TowerDoorLockHandleReplace','NLEDumploadResistorReplace','NLEMCCBReplace','NLECTDCNCB Replace','NLESurgeProtectorReplace','NLEDCUPSControllerReplace','NLEDCUPSSensorBoardReplace','NLEEMCFilterReplace','TowerSectionModuleReplace','InternalChainHoistDeflectorReplace','PitchCylinderAssemblyReplace','DrainPipeAssemblyReplace','RotorLockManifoldAssemblyReplace','ControlPanelVFDReplace','CMSPowerSupplyUnitReplace','HydraulicCabinetStarterMotorReplace','SwitchGearRelayReplace','YawModuleVibrationSensorReplace','BusbarCabinetCircuitBreakerReplace','GroundControllerCabinetStarterMotorReplace','HydUnitYawSystemReplace','GearOfflineMotorReplace','RotatingTransferPipeO-RingReplace','BatteryPack96VStandardReplace','NoseConicalNormalCapReplace','HydManifoldReplace','PitchCYLRodSealKit_mat','BladeBearingTorqueArmBushing','BladeBearingTorqueArmAssembly','BladeBearingTorqueArm','TowerPlatformBushingMat','GearDrainPFTTBushingMat','YAWSensorModule_mat','TowerAccelerometer_mat','LightCTU_mat','WICStuffBox_mat','CMSEthernet_mat','NoseRepairKit_mat','TowerSealingLip_mat','ShaftSealsplit_mat','FiberRotaryJoint_mat','BracketExtChainBox_mat','FlyWheel_mat','APSFuse_mat','PSCFuse_mat','TowerServiceLiftFuse_mat','BladeIcingFuse_mat','YawGreaseWheel_mat','BladeLightReceptorScrew_mat','CMSFuse_mat','HUBFuse_mat','HydraulicAccumulator_mat','APSContactor_mat','APSIOCardUPS_mat','APSUPSBattery_mat','APSCTModule_mat','ARCNetCable_mat','BldCntrlUpgrCable_mat','APSRelay_mat','BladeLubCableReplace','ArcDetector_mat','BladeLPSReplace','NLESlipringUnitReplace','NLESlipringUnitBrushesReplace','AuxTrafoPT100Sensor_mat','HubHeaterWithFanReplace','HUBUPSControlUnitReplace','HubSensorBoardReplace','HubRedudancyModuleReplace','HubRelayModuleReplace','TowerFiberCableReplace','TowerColliCableReplace','TowerPaintConsumption','TowerDamperRubberSleeveReplace','MainCabinetCBMotorReplace','CACCoolingPipeReplace','HydSystemSealMaterial','HydraulicSystemConnector_mat','HydRTUSealReplace','HighSpeedCouplingReplace','HydPipeAssemblyReplace','GearOilHoseReplace','HydOilHoseReplace','SMTErosionRepair','PowertrainSpeedSensorReplace','CACO-RingReplace','HubLightElementReplace','NacelleFloorBasePlateNutAssy','CubePowerArcVentAssy','BBGreaseCollectionCanAssy','NacelleControllerEKEYSecuringKIT'"

In [92]:
df['Itemnumber'].nunique()

8129

Frame the query to be run in Snowflake

In [93]:
df.dropna(inplace=True)

In [94]:
merged_ids = ",".join("'" + df['Itemnumber'].astype(str) + "'")
merged_ids

"'107033','760306','76221907','76221971','103566','105203','105243','105244','107045','107062','107064','107075','107080','107081','107085','107086','107087','107088','107089','107090','107091','107092','107146','107152','107155','107162','107163','107164','107166','107170','107173','107174','107178','107247','107317','151902','151903','151906','151907','29001915','29001916','29013250','29018808','29018809','29055811','29078688','29085546','29088145','29091280','29092454','29092464','29094865','29098041','29101168','29106634','29108850','29142587','29151345','29185782','29185818','29195706','34721','34729','34736','34744','60036055','60037816','60042600','60046041','60050981','60068860','60078227','60079086','60079090','60079092','60079328','60091771','60113590','60113591','60114065','60120942','70000147','70590033','70590034','29155641','29195008','108613','108614','110912','110915','110915REN','29058278','29060554','29060555','29060556','29080628','29080630','29084354','29084355','29084548','29087895','29087901','29090196','29101283','29103044','29105434','29111326','29115632','29115633','29115911','29119113','29124937','29124952','29133171','29133172','29144119','300042437','300042438','60043278','60067736','60076680','60114028','108381','108382','108385','108388','194312','194312REN','194314','194314REN','29079820','29088926','29088994','29096815','29096815REN','29103236','29103236REN','29103488','29103488REN','29114654','29114654REN','29190837','29300434','300036987','60078979','880407','29004588','29004589','29031014','29227225','29229933','100810','100814','103519','103520','104822','104872','104949','105026','107042','107185','107314','20028997','29000805','29000806','29000808','29002098','29002146','29002148','29002149','29002778','29002880','29011467','29011608','29011609','29016545','29024270','29024271','29057268','29058623','29058831','29059964','29059965','29059966','29059967','29060179','29060191','29060193','29060194','29060195','29060196','29060428','29060438','29060441','29060443','29060444','29060445','29061992','29061993','29062031','29062032','29062033','29062034','29062035','29062036','29062037','29062038','29062039','29062050','29062051','29062052','29062053','29062054','29082689','29103513','29103605','29113078','29115148','29117776','29117777','29117778','29117779','29135454','29141562','29141563','29156558','29187950','29188425','29203855','29209723','29294327','75420006','75420006REN','761495','761496','880599','880600','882816','882816REN','882817','882818','882819','882820','883210','883211','883292','100815','103057','103058','103125','103421','103422','103457','103473','103502','103549','103588','103608','104808','104809','104810','104811','104818','104819','104864','104865','104866','104867','104873','104935','105000','105004','107043','107071','107095','107229','107270','107309','107321','107322','107325','107339','114470','114470REN','114483','119142','11914200','11914200REN','119142REN','119143','119143REN','29000406','29002097','29002147','29007122','29021726','29024261','29057264','29057265','29057266','29057267','29059950','29059951','29059952','29059953','29059954','29059955','29059956','29059957','29059958','29059959','29059960','29059961','29059962','29059963','29060171','29060172','29060173','29060174','29060175','29060176','29060177','29060178','29060423','29060425','29060426','29060427','29060429','29060430','29060431','29060432','29060433','29060435','29060436','29060437','29060866','29060867','29060868','29060869','29060969','29060980','29060981','29060983','29060984','29061960','29062000','29062001','29062002','29062828','29062828REN','29062829','29063413','29078506','29078506REN','29078507REN','29079658','29079659','29079937','29079955','29079955REN','29079956','29079956REN','29080783','29080783REN','29080784','29093709','29099257','29099257REN','29099258','29099390','29099391','29102035','29103492','29104437','29104452','29110341','29110342','29110343','29110344','29110345','29110346','29110782','29110782REN','29110783','29110783REN','29115147','29115149','29116569','29116650','29116652','29116653','29117439','29117440','29117441','29117442','29117443','29117772','29117773','29117774','29117775','29123828','29123872','29123873','29125973','29127859','29128036','29128039','29128040','29128041','29128043','29128046','29128057','29128171','29128200','29128203','29128214','29133127','29137366','29141560','29154781','29185425','29185950','29185951','29189108','29189113','29197019','29203980','29252566','29287481','60051876','60069297','60100020','60110099','60110100','70002347','721137','730205','75420003','789256','789257','789404','78940400','789405','880750','883256','100804','100805','105005','105006','105008','29024219','29045977','104695','104884','104891','104904','104932','104941','104980','114297','114704','195156','195157','29000751','29000752','29000753','29013113','29020964','29020965','29106586','29106726','29205268','60102405','29203997','10105403','10105403REN','101267','101269','101284','101286','193867','193868','193951','193951REN','193952','193952REN','193953','193953REN','193954','193983','193983REN','193984','193984REN','193985','193985REN','193999','29025288','29025289','29048918','29058152','29058153','29063209','29085645','29099772','29114050','29116494','29131678','29192833','29235461','29235462','29245361','29351146','46346','46347','46348','46349','61333','70000506','70530204','70530206','70531079','753045','753114','753326','753903','101011','101011REN','103968','103968REN','104009','104009REN','104067','109035','109035REN','109058','109212','109926','109953','109953REN','109959','109965','109967','109968','110095','110097','110102','110119','110162','110163','29008445','29008446','29010892','29012353','29023550','29039390','29046734','29046735','29055966','29064377','29077648','29086411','29086516','29086517','29086518','29086521','29086523','29087190','29087191','29093553','29097336','29111518','29117378','29117379','29117400','29119308','29123783','29147397','29156832','29198264','29211169','29251004','29251005','764295','109062','149391','149394','149395','29002683','29021868','29021869','29021960','29021962','29021963','29025124','29025125','29025294','29025295','60103108','60103111','149090','149110','149115','149119','149151','149163','149204','149207','149208','149209','149211','29002266','29021200','29021201','29021202','29021203','29021210','29021217','29079603','29079609','29084614','29088588','29097359','29097715','29099546','29102552','29102560','29104050','29104054','29107715','29111269','29114742','29116621','29120703','29120704','29120705','29120921','29139026','29228325','60030146','60037472','60049423','60096947','60120883','60120884','60120885','101151','101156','10205208','10205208REN','105142','105184','105602','112075','115245','115259','115269','115271','115305','188640','193869','193869REN','193990','194024','29016709','29017214','29017214REN','29017215','29017215REN','29017216','29018248','29018394','29019364','29029928','29034518','29043941','29092396','29092398','29096371','29104896','29106749','29106751','29108161','29110954','29120336','29120348','29145764','29157661','29184348','29184349','29184380','29184381','29202966','29224415','29237855','29237856','29265150','29269328','29340115','29348518','60043186','60046204','60063919','60064154','60073425','60073425REN','60076234','60076438','60098813','60103464','60108771','60112650','60112650REN','60120512','60120512REN','60120688','76000560','10205209','10208621','10209205','103712','103722','103722REN','103723','105187','105601','105601REN','109555','109921','109986','110038','110039','112007','112032','112049','112081','116345','29000091','29016727','29018113','29029879','29034525','29055134','29064347','29085599','29101696','29106591','29119520','29119548','29120335','29125954','29234609','29234609REN','29240890','60037824','60061704','60065190','60092037','60098815','60099187','60099209','60112675','60112676','60112677','60120595','76000542','76000558','76000559','880194','880199','880334','880336','880348','880701','880704','883272','149062','149071','149078','149079','149085','149088','149091','149092','149093','149094','149095','149096','149118','149171','149175','149341','149342','149345','149346','29003872','29004825','29013586','29013587','29013588','29021511','29021512','29021513','29021522','29021523','29021524','29021541','29079599','29081629','29084613','29090022','29091253','29092901','29096794','29096809','29096820','29096821','29096822','29096845','29096851','29096853','29096854','29097712','29098576','29101639','29102305','29104030','29104059','29104060','29106992','29107507','29118746','29120701','29120953','29125951','29235763','29235765','60037758','60058893','60059781','60060012','60069151','60078080','60096951','60113672','60120401','29231817','70002460','10204904','10204904REN','10209196','115242REN','115253','115254','115255','115256','115257','115257REN','115267','115278','115286','193988','193993','193993REN','193994','193995','193995REN','193996','194014','194015','194020','194022','194022REN','194023','194023REN','194037','194046','194047','194049','194067','194067REN','194068','194070','194074','194074REN','194078','194079','194084','194084REN','194086','194086REN','194096','194096REN','194097','29001285','29004585','29005012','29005013','29006499','29006499REN','29006741','29006741REN','29008119','29008330','29012941','29012941REN','29012942','29012942REN','29014163','29014163REN','29014164','29014164REN','29014166','29014166REN','29020308','29020308REN','29020351','29020351REN','29049984','29081688','29086323','29089767','29091968','29093588','29094165','29094172','29094427','29095317','29095317REN','29095420','29095440','29095440REN','29095441','29095443','29095443REN','29097531','29099545','29102297','29103008REN','29103985','29107928','29108458','29108459','29108464','29108465','29108465REN','29110010','29112326','29112346','29113019','29113019REN','29113811','29113811REN','29113813','29113814','29113891','29115835','29116027','29116027REN','29116058','29118148','29118149','29118155','29118192','29118530','29133357','29133358','29133359','29133471','29133472','29133473','29158374','29158375','29158379','29175363','29187209','29188159','29189842','29190780','29197886','29206293','29206294','29227223','29227226','29243978','29248984','29248986','29248987','29248988','29248989','29248990','29248991','29248992','29259638','29259639','29259640','29259642','29260473','29260573','29260574','29260575','29276825','29316975','29316976','29317579','29317580','29317581','29317582','29317584','29318280','29318281','300009496','60036158','60036158REN','60050688','60055646','60060988','60062031','60065348','60065808','60067483','60077017','60077252','60077352','60091176','60091176REN','60091177','60099481','60104637','60109338','M000737923 ','118200','118200REN','11870141','11870146','11880015','11880016','11880383','11880384','11880384REN','11880441','11880442','11880636','11880637','11880639','11880707','29099279','29318499','101006','101006REN','101008','101008REN','101095','101110','101128','101129','101163','101187','115232','115232REN','115235','115235REN','115265','115301','193955','193980','193982','193987','193999REN','194019','194503','194971','194975','29010485','29013731','29064728','29088628','29089649','29092394','29095278','29114051','29114051REN','29189881','29224266','60120557','70000835','101131','101131REN','101143','101143REN','101164','101178','101178REN','101179','101180','105151','115273','115273REN','115295','115295REN','29023514','29053407','29090286','29093035','29097147','29118297','29209807','60093993','60093993REN','60099214','60103122','60108419','76401021','781054','101003','10101656','101197','29001954','29081545','29084365','29085708','29309041','76400705','10204728','10206649','106414','106414REN','106415REN','106419','106423','106423REN','106426','106479','106479REN','29015366','29015367','29048176','29048177','29081070','29085471','29087734','29090266','29091282','29091977','29093337','29097451','29097452','29097548','29098492','29102164','29103139','29103139REN','29103140REN','29106601','29106702','29175370','29176470','29186809','29190433','299794','60009297REN','60009298','60009298REN','60009301','60009301REN','60009313','60009341','60009341REN','60009345','60009349','60009349REN','60030163','60030164','60031970','60031971','60032066','60032067','60032980','60032980REN','60092567','60092777REN','60112408','70000713','703592','737260','737260REN','737268','737270','782203','835779','835779REN','835783','835784','835784REN','872148','872300','872300REN','872305','872310','872310REN','872431','872431REN','880569','888105','951850','951851','29316424','10100155','114241','114248','114250','114254','114257','114259','114260','114261','114264','114941','114952','114953','114954','116647','193863','193883','193891','29000334','29089692','60030079','60030144','60030521','60032181','60032182','60032639','60032642','60035104','60035105','60037940','60120757','V64000596','29134482','114279','114700','114701','114722','114724','60009279','60009280','60009281','60009282','60009283','60098250','60108876','60114026','117066','184959','185049','185243','185379','188251','189527','189797','29014103','29082251','29378666','60004433','60004434','60004444','60004778','60004779','60005193','60005358','60005360','60005751','60110880','117032','185411','29208311','70000416','116608','117038','117038REN','117042','117042REN','117043','117044','117047','117055','117063','117067','117067REN','184950','184953','185027','185027REN','185057','185059','185071','185071REN','185202','185219','185224','185285','188253','188254','188265','188267','188268','189761','189761REN','189766','189766REN','29003123','29009129','29014942','29025920','29031956','29031958','29032511','29032512','29032513','29032514','29045325','29081228','29095363','29095884','29113008','29113009','29120323','29120325','29125017','29175963','29197721','29215218','29299538','60005681','70000415','765335','184808','29121817','29049678','29057272','29064722','880373','880379','880485','880497','880498','880508','880527','880560','883257','883267','883275','29034438','60120770','781687','883242','10100501','185099','29009562','782162','29222365','60073486','881844','881846','881854','883141','29017492','29019710','29020561','29050548','29060371','29060373','29083934','29085295','29087965','29090703','29090705','29090705REN','29090706','29090707','29090707REN','29090724','29092426','29101991','29109567','29122454','29190051','29198055','29211349','29241199','29241201','29293475','60045272','60050462','60069223','60069224','60069225','753075','753077','753078','753081','753082','753246','753267','753267REN','753278','753366','753479','753479REN','753480','753481','753483','753627','753661','753662','753829','753852','753853','753854','753865','753943','753946','753950','753960','753962','29022676','753247','753247REN','753656','753659','753686','753693','788431','788483','193508','29024165','29024166','29024167','29024168','184940','185105','189243','29057022','29085113','29085118','29085120','29085131','29086417','29087077','29088388','29094129','29094886','29095172','29095199','29095226','29095283','29095325','29095326','29095368','29095389','29095393','29095990','29095992','29096073','29096082','29097175','29098440','29098440REN','29099593','29102643','29102647','29103813','29105276','29105297','29106646','29106684','29107520','29107529','29110852','29113619','29113620','29113626','29116056','29116430','29117966','29134203','29156397','29190453','29190454','29191443','29201063','60004863','755360','755361','755787','75578703','765761','76576103','7657610301','765778','765779','785724','785724REN','785725','785726','785790','78579003','7857900301','107032','141024','149047','14904740','14904750','149258','14925840','14925850','149261','60050845','60073006','149190','149191','149265','149266','149276','29078564','29091256','29091303','29092989','29092995','29101905','29102911','29126989','29300903','29350049','29527','60038712','149216','141023','149139','14913926','14913950','60052021','149116','149156','149189','149253','149254','149264','29023724','29092990','29247826','29276026','149168','29230048','213620','230097','186181','186181REN','186209','186209REN','186417','189196','29151060','188476','188660','29083080','29085013','29089384','29097212','29175253','29198962','60000702','60106093','29011523','29023429','29058693','29083083','29101818REN','29181062','186346','186420','188419','188458','188473','189177','189178','29017618','29059256','29059297','29079607','29079608','29084983','29085146','29085176','29086730','29087711','29088382','29088520','29091649REN','29092319','29093137','29095610','29095809','29097214','29097216','29097219','29097435','29099402','29100936','29101098','29102054','29102056','29102102','29105553','29105569','29105682','29105805','29106508','29107431','29107460','29107538','29109924','29113470','29114264','29114696','29120755','29123349','29124386','29138877','29175290','29175426','29175433','29185665','29191007','29191051','29191409','29192759','29192762','29192985','29193030','29211366','29215450','29216726','29279826','60000694','60000695','60000697','60000703','60000704','60000707','60031944','60031945','60114156','186414','186414REN','51029109REN','51313302','51313302REN','51313303','51313303REN','51315301REN','51315302','51315302REN','51322001','51322001REN','51322002','51322020','51322020REN','51322021','51322022','51322022REN','51322023','51322023REN','51322024','51322025','51322025REN','51322027','51322027REN','51322029','51323201','51323201REN','51323401','51323401REN','51606104','51606106','51606106REN','51606108','51606109','51606205','51606206','51613705','51613705REN','51622005','51625502','51702001','51702001REN','51707301REN','51021703','51022702','51023602','51026403','51026505','51027903','51027903REN','51029101','51029101REN','51029102REN','51029107','51029107REN','51029110','51029110REN','51033401','51039601REN','51039602','51039602REN','51321502','51340901','51340901REN','51341501','51341501REN','51360102','51360102REN','51360304','51560109','51600301','51600302','51600303','51600303REN','51600304','51622104','51625101','51700101','51700402','51701601','51701701','51702601','51702601REN','51706501','51707301','51811702','51811901','51820003','51830103','51840102','51840102REN','60015771','60015771REN','60097464','70002264','70002268','51321801REN','51321802','51321802REN','51321803REN','51321804REN','51321805REN','51321806','51321806REN','51611804','51811101','51811201','51811301','51811303','51811401','764811','764813','51022802','51029407','51029407REN','51030805','51030805REN','51030806','51030901','51030902','51030902REN','51031002','51031004','51031805','51031814','51031814REN','51031815','51031815REN','51031817','51031817REN','51032601','51032701','51032801','51033201','51033202','51033203','51033301','51033302','51033501','51034103REN','51036001','51036001REN','51036002','51036002REN','51036701','51041402','51041403','51041403REN','51041602','51041602REN','51042001','51043102','51043103','51043104','51043104REN','51043501','51044004','51044004REN','51046001REN','51046002','51046002REN','51048002','51048002REN','51315303','51325103','51325103REN','51325301','51360104','51360104REN','51360301','51360301REN','51360302','51360302REN','51360303','51600104','51600104REN','60097264','60097288','60097288REN','29015534','51522001REN','51522002','51522101','51522201','51522301','51522302','51522302REN','51701501','51701501REN','51035401','51038402','51038502','51038601','51038701','51038801','51038901','51039001','51039101','51039402','51605001','51605002','51605101','29035708','29057981','70002391','60113038','29022772','29023537','768425','60007759','60008264','749114','746109','29000951','29006948','29012383/0130','29023607

In [95]:
snflk_query = '''select distinct
part_number as parent, part_name as parent_name, 
parent as material, parent_description as material_name,
component_number as child_number, 
TRIM(REPLACE(structure_name, '|', '')) as child_name
from OFFSHORE_READINESS.DATAMART.DIM_SAP_BOM_EXPLOSION
where 1=1
and year(bom_valid_to)=9999
and parent is not null
and parent != part_number
and parent in ({})
'''.format(merged_ids)
print(snflk_query)

select distinct
part_number as parent, part_name as parent_name,
parent as material, parent_description as material_name,
component_number as child_number,
TRIM(REPLACE(structure_name, '|', '')) as child_name
from OFFSHORE_READINESS.DATAMART.DIM_SAP_BOM_EXPLOSION
where 1=1
and year(bom_valid_to)=9999
and parent is not null
and parent != part_number

Execution flow for one material

In [96]:
df['Itemnumber'].values[0]

'107033'

In [97]:
parents_df = pd.DataFrame()
for itemnumber in df['Itemnumber'].values:
    parents_df = pd.concat([parents_df, df_parent.loc[df_parent['parent_material']==itemnumber]])
parents_df.head()

      parent_material child_material
12543          760306         103850
12544          760306         103852
12545          760306         105717
12546          760306         107028
12547          760306         108088

In [98]:
p1 = parents_df.loc[parents_df['parent_material']=='760306']
p1.head(2)

      parent_material child_material
12543          760306         103850
12544          760306         103852

In [101]:
df_order_counts.columns, df_order_counts.shape

(Index(['Material', 'MaterialText', 'order_counts'], dtype='str'), (67396, 3))

In [102]:
type(p1['parent_material'].values[0]), type(df_order_counts['Material'].values[0])

(str, int)

In [103]:
m1 = parents_df.merge(df_order_counts, left_on='parent_material', right_on='Material', how='inner')
m1.head()

,parent_material,child_material,Material,MaterialText,order_counts
0,29012383/0130,S091823,29012383/0130,CABLE -120-02-W2,587
1,29012383/0130,S095170,29012383/0130,CABLE -120-02-W2,587
2,29012383/0130,S099116,29012383/0130,CABLE -120-02-W2,587
3,29012383/0133,195248,29012383/0133,CABLE -615-06-05-W2,28
4,29012383/0133,S093197,29012383/0133,CABLE -615-06-05-W2,28

In [104]:
m1.shape

(221, 5)

In [105]:
df_order_counts.columns, parents_df.columns

(Index(['Material', 'MaterialText', 'order_counts'], dtype='str'),
 Index(['parent_material', 'child_material'], dtype='str'))

In [107]:
df_order_counts['Material'].nunique()

67396

In [128]:
m2 = m1.merge(df_order_counts, left_on='child_material', right_on='Material', how='left', suffixes=('_parent', '_child'))
m2.head()

,parent_material,child_material,Material_parent,MaterialText_parent,order_counts_parent,Material_child,MaterialText_child,order_counts_child
0,29012383/0130,S091823,29012383/0130,CABLE -120-02-W2,587,NaN,NaN,NaN
1,29012383/0130,S095170,29012383/0130,CABLE -120-02-W2,587,S095170,SHRINK PRINT YE Ø4.7-9.5 ZH,119.0
2,29012383/0130,S099116,29012383/0130,CABLE -120-02-W2,587,S099116,"HEAT SHRINKABLE TUBE,9.5 mm,2:1,WHITE",75.0
3,29012383/0133,195248,29012383/0133,CABLE -615-06-05-W2,28,NaN,NaN,NaN
4,29012383/0133,S093197,29012383/0133,CABLE -615-06-05-W2,28,S093197,"TERMINAL,LUG,END,0.5 mm2,8 mm",298.0

In [112]:
m2.dropna(subset=['Material_child'], inplace=True)
m2.shape

(173, 8)

In [114]:
m2.drop(columns=['Material_parent','Material_child'], inplace=True)
m2.head()

,parent_material,child_material,MaterialText_parent,order_counts_parent,MaterialText_child,order_counts_child
1,29012383/0130,S095170,CABLE -120-02-W2,587,SHRINK PRINT YE Ø4.7-9.5 ZH,119.0
2,29012383/0130,S099116,CABLE -120-02-W2,587,"HEAT SHRINKABLE TUBE,9.5 mm,2:1,WHITE",75.0
4,29012383/0133,S093197,CABLE -615-06-05-W2,28,"TERMINAL,LUG,END,0.5 mm2,8 mm",298.0
5,29012383/0133,S094667,CABLE -615-06-05-W2,28,SHRINK HEAT 2:1 PO9.5X0.6 BLACK,77.0
6,29012383/0133,S099113,CABLE -615-06-05-W2,28,HEAT SHRINK 3.2mm 2:1 WHITE,16.0

In [115]:
df1 = df[['Serviceeventcode','Itemnumber']]
df1.head()

      Serviceeventcode Itemnumber
0  BladeBearingReplace     107033
1  BladeBearingReplace     760306
2  BladeBearingReplace   76221907
3  BladeBearingReplace   76221971
4       GenBearReplace     103566

In [116]:
m3 = m2.merge(df1, how='inner', left_on='parent_material', right_on='Itemnumber', suffixes=('_m2', '_df1'))
m3.head()

,parent_material,child_material,MaterialText_parent,order_counts_parent,MaterialText_child,order_counts_child,Serviceeventcode,Itemnumber
0,29012383/0130,S095170,CABLE -120-02-W2,587,SHRINK PRINT YE Ø4.7-9.5 ZH,119.0,HubCANCableReplace,29012383/0130
1,29012383/0130,S099116,CABLE -120-02-W2,587,"HEAT SHRINKABLE TUBE,9.5 mm,2:1,WHITE",75.0,HubCANCableReplace,29012383/0130
2,29012383/0133,S093197,CABLE -615-06-05-W2,28,"TERMINAL,LUG,END,0.5 mm2,8 mm",298.0,CCICableReplace,29012383/0133
3,29012383/0133,S094667,CABLE -615-06-05-W2,28,SHRINK HEAT 2:1 PO9.5X0.6 BLACK,77.0,CCICableReplace,29012383/0133
4,29012383/0133,S099113,CABLE -615-06-05-W2,28,HEAT SHRINK 3.2mm 2:1 WHITE,16.0,CCICableReplace,29012383/0133

In [132]:
# No parent child relationship exists in a same event with order countsss
m3a = m3.merge(df1, left_on=['Serviceeventcode','child_material'], right_on=['Serviceeventcode','Itemnumber'], how='inner')
m3a.head()

Empty DataFrame
Columns: [parent_material, child_material, MaterialText_parent, order_counts_parent, MaterialText_child, order_counts_child, Serviceeventcode, Itemnumber_x, Itemnumber_y]
Index: []

In [118]:
m3.shape, m3['Serviceeventcode'].unique()

((173, 8),
 <ArrowStringArray>
 [  'HubCANCableReplace',      'CCICableReplace',     'ConvCableReplace',
  'PitchHydCableReplace', 'BladeLubCableReplace']
 Length: 5, dtype: str)

In [120]:
m3.loc[m3['Serviceeventcode']=='ConvCableReplace']

,parent_material,child_material,MaterialText_parent,order_counts_parent,MaterialText_child,order_counts_child,Serviceeventcode,Itemnumber
22,29012710/0110,S099118,CABLE -405-04-01-F2:2,3,HEAT SHRINK 19.0mm 2:1 WHITE,9.0,ConvCableReplace,29012710/0110
23,29012710/0145,S094414,CABLE -405-04-01-R1:6,29,TERMINAL KRF 16mm2 M8 90DEG,11.0,ConvCableReplace,29012710/0145
24,29012710/0145,S099117,CABLE -405-04-01-R1:6,29,"HEAT SHRINKABLE TUBE,12.7 mm,2:1,WHITE",40.0,ConvCableReplace,29012710/0145
25,79541002/101,S099117,CABLE 405-02-05-Q14-146.1:T3,3,"HEAT SHRINKABLE TUBE,12.7 mm,2:1,WHITE",40.0,ConvCableReplace,79541002/101

In [123]:
req_cols = ['Serviceeventcode','parent_material','order_counts_parent','order_counts_child']
m4 = m3[req_cols]
m4.head()

     Serviceeventcode parent_material  order_counts_parent  order_counts_child
0  HubCANCableReplace   29012383/0130                  587               119.0
1  HubCANCableReplace   29012383/0130                  587                75.0
2     CCICableReplace   29012383/0133                   28               298.0
3     CCICableReplace   29012383/0133                   28                77.0
4     CCICableReplace   29012383/0133                   28                16.0

In [129]:
pc = m4.groupby(['Serviceeventcode','parent_material']).agg({'order_counts_parent':'mean', 'order_counts_child':'sum'}).reset_index()
pc['parent_to_child'] = pc['order_counts_parent'] / pc['order_counts_child']
pc.head()

,Serviceeventcode,parent_material,order_counts_parent,order_counts_child,parent_to_child
0,BladeLubCableReplace,29012383/0100,465.0,651.0,0.714286
1,BladeLubCableReplace,29012383/0126,380.0,390.0,0.974359
2,CCICableReplace,29012383/0133,28.0,466.0,0.060086
3,CCICableReplace,29012385/0105,310.0,540.0,0.574074
4,CCICableReplace,29012387/0100,17.0,3.0,5.666667

In [137]:
eves= pc.loc[pc['parent_to_child']>0.5,'Serviceeventcode'].unique()
m3.loc[m3['Serviceeventcode'].isin(eves)]

,parent_material,child_material,MaterialText_parent,order_counts_parent,MaterialText_child,order_counts_child,Serviceeventcode,Itemnumber
0,29012383/0130,S095170,CABLE -120-02-W2,587,SHRINK PRINT YE Ø4.7-9.5 ZH,119.0,HubCANCableReplace,29012383/0130
1,29012383/0130,S099116,CABLE -120-02-W2,587,"HEAT SHRINKABLE TUBE,9.5 mm,2:1,WHITE",75.0,HubCANCableReplace,29012383/0130
2,29012383/0133,S093197,CABLE -615-06-05-W2,28,"TERMINAL,LUG,END,0.5 mm2,8 mm",298.0,CCICableReplace,29012383/0133
3,29012383/0133,S094667,CABLE -615-06-05-W2,28,SHRINK HEAT 2:1 PO9.5X0.6 BLACK,77.0,CCICableReplace,29012383/0133
4,29012383/0133,S099113,CABLE -615-06-05-W2,28,HEAT SHRINK 3.2mm 2:1 WHITE,16.0,CCICableReplace,29012383/0133
5,29012383/0133,S099116,CABLE -615-06-05-W2,28,"HEAT SHRINKABLE TUBE,9.5 mm,2:1,WHITE",75.0,CCICableReplace,29012383/0133
6,29012385/0105,S091884,CABLE -615-06-11-W2 L=7M,310,CABLE CAN M12 MALE L=7M UL,2.0,CCICableReplace,29012385/0105
7,29012385/0105,S094090,CABLE -615-06-11-W2 L=7M,310,PHOENIXPLUG QC0.5/2-ST-3.81 BK,267.0,CCICableReplace,29012385/0105
8,29012385/0105,S094667,CABLE -615-06-11-W2 L=7M,310,SHRINK HEAT 2:1 PO9.5X0.6 BLACK,77.0,CCICableReplace,29012385/0105
9,29012385/0105,S095170,CABLE -615-06-11-W2 L=7M,310,SHRINK PRINT YE Ø4.7-9.5 ZH,119.0,CCICableReplace,29012385/0105
10,29012385/0105,S099116,CABLE -615-06-11-W2 L=7M,310,"HEAT SHRINKABLE TUBE,9.5 mm,2:1,WHITE",75.0,CCICableReplace,29012385/0105
11,29012387/0100,S099125,CABLE -615-10-07-W1,17,CABLE MARKS 35X20-60mm YELLOW,3.0,CCICableReplace,29012387/0100
12,746110/106,S094664,CABLE -615-06-05-W3,17,SHRINK HEAT 2:1 PO6.4X0.45,88.0,CCICableReplace,746110/106
13,746110/106,S099116,CABLE -615-06-05-W3,17,"HEAT SHRINKABLE TUBE,9.5 mm,2:1,WHITE",75.0,CCICableReplace,746110/106
14,795210/132,S094090,CABLE -615-04-33-W2,5,PHOENIXPLUG QC0.5/2-ST-3.81 BK,267.0,CCICableReplace,795210/132
15,795210/132,S095170,CABLE -615-04-33-W2,5,SHRINK PRINT YE Ø4.7-9.5 ZH,119.0,CCICableReplace,795210/132
16,795210/132,S099116,CABLE -615-04-33-W2,5,"HEAT SHRINKABLE TUBE,9.5 mm,2:1,WHITE",75.0,CCICableReplace,795210/132
17,795210/135,S093197,CABLE -615-04-01-W3,1,"TERMINAL,LUG,END,0.5 mm2,8 mm",298.0,CCICableReplace,795210/135
18,795210/135,S094667,CABLE -615-04-01-W3,1,SHRINK HEAT 2:1 PO9.5X0.6 BLACK,77.0,CCICableReplace,795210/135
19,795210/135,S099113,CABLE -615-04-01-W3,1,HEAT SHRINK 3.2mm 2:1 WHITE,16.0,CCICableReplace,795210/135
20,795210/135,S099116,CABLE -615-04-01-W3,1,"HEAT SHRINKABLE TUBE,9.5 mm,2:1,WHITE",75.0,CCICableReplace,795210/135
21,795210/136,S099117,CABLE -615-04-03-W2,1,"HEAT SHRINKABLE TUBE,12.7 mm,2:1,WHITE",40.0,CCICableReplace,795210/136
22,29012710/0110,S099118,CABLE -405-04-01-F2:2,3,HEAT SHRINK 19.0mm 2:1 WHITE,9.0,ConvCableReplace,29012710/0110
23,29012710/0145,S094414,CABLE -405-04-01-R1:6,29,TERMINAL KRF 16mm2 M8 90DEG,11.0,ConvCableReplace,29012710/0145
24,29012710/0145,S099117,CABLE -405-04-01-R1:6,29,"HEAT SHRINKABLE TUBE,12.7 mm,2:1,WHITE",40.0,ConvCableReplace,29012710/0145
25,79541002/101,S099117,CABLE 405-02-05-Q14-146.1:T3,3,"HEAT SHRINKABLE TUBE,12.7 mm,2:1,WHITE",40.0,ConvCableReplace,79541002/101
156,29012383/0100,S09002320,CABLE -105-02-05-W1,465,PROTECTIVE COVER DSUB 9 PA,21.0,BladeLubCableReplace,29012383/0100
157,29012383/0100,S09002376,CABLE -105-02-05-W1,465,HOUSING DSUB 9 IP67 PA,18.0,BladeLubCableReplace,29012383/0100
158,29012383/0100,S092535,CABLE -105-02-05-W1,465,PLUG SUB-D 9-POL FEMALE,6.0,BladeLubCableReplace,29012383/0100
159,29012383/0100,S094648,CABLE -105-02-05-W1,465,SHRINK HEAT 2:1 PO20X0.7 BLACK,63.0,BladeLubCableReplace,29012383/0100
160,29012383/0100,S094649,CABLE -105-02-05-W1,465,SHRINK HEAT 2:1 PO12X0.7 BLACK,47.0,BladeLubCableReplace,29012383/0100
161,29012383/0100,S094664,CABLE -105-02-05-W1,465,SHRINK HEAT 2:1 PO6.4X0.45,88.0,BladeLubCableReplace,29012383/0100
162,29012383/0100,S094668,CABLE -105-02-05-W1,465,SHRINK HEAT 2:1 PO6X0.4 BLACK,198.0,BladeLubCableReplace,29012383/0100
163,29012383/0100,S095170,CABLE -105-02-05-W1,465,SHRINK PRINT YE Ø4.7-9.5 ZH,119.0,BladeLubCableReplace,29012383/0100
164,29012383/0100,S099113,CABLE -105-02-05-W1,465,HEAT SHRINK 3.2mm 2:1 WHITE,16.0,BladeLubCableReplace,29012383/0100
165,29012383/0100,S099116,CABLE -105-02-05-W1,465,"HEAT SHRINKABLE TUBE,9.5 mm,2:1,WHITE",75.0,BladeLubCableReplace,29012383/0100
166,29012383/0126,S09002320,CABLE -105-02-05-W2,380,PROTECTIVE COVER DSUB 9 PA,21.0,BladeLubCableReplace,29012383/0126
167,29012383/0126,S09002376,CABLE -105-02-05-W2,380,HOUSING DSUB 9 IP67 PA,18.0,BladeLubCableReplace,29012383/0126
168,29012383/0126,S092535,CABLE -105-02-05-W2,380,PLUG SUB-D 9-POL FEMALE,6.0,BladeLubCableReplace,29012383/0126
169,29012383/0126,S094648,CABLE -105-02-05-W2,380,SHRINK HEAT 2:1 PO20X0.7 BLACK,63.0,BladeLubCableReplace,29012383/0126
170,29012383/0126,S094664,CABLE -105-02-05-W2,380,SHRINK HEAT 2:1 PO6.4X0.45,88.0,BladeLubCableReplace,29012383/0126
171,29012383/0126,S095170,CABLE -105-02-05-W2,380,SHRINK PRINT YE Ø4.7-9.5 ZH,119.0,BladeLubCableReplace,29012383/0126
172,29012383/0126,S099116,CABLE -105-02-05-W2,380,"HEAT SHRINKABLE TUBE,9.5 mm,2:1,WHITE",75.0,BladeLubCableReplace,29012383/0126